export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const MOBILE_BREAKPOINT = process.env.NEXT_PUBLIC_MOBILE_BREAKPOINT;
export const TABLET_BREAKPOINT = process.env.NEXT_PUBLIC_TABLET_BREAKPOINT;
export const DESKTOP_BREAKPOINT = process.env.NEXT_PUBLIC_DESKTOP_BREAKPOINT;
